"""add podcast description

Revision ID: 2437946eb6eb
Revises: cd73e648ad4c
Create Date: 2020-09-17 23:38:49.699650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2437946eb6eb'
down_revision = 'cd73e648ad4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('description', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'description')
    # ### end Alembic commands ###
