"""test

Revision ID: 269a0c78090a
Revises: 8c0c6a747cb2
Create Date: 2020-09-27 19:31:01.798485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269a0c78090a'
down_revision = '8c0c6a747cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    print("ta mere")
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
