"""retweet

Revision ID: a1322d204558
Revises: 9a165430074f
Create Date: 2020-10-27 17:26:15.801707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1322d204558'
down_revision = '9a165430074f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserEpisodeRetweet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name=op.f('fk_UserEpisodeRetweet_episode_id_episode')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_UserEpisodeRetweet_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'episode_id', name=op.f('pk_UserEpisodeRetweet'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserEpisodeRetweet')
    # ### end Alembic commands ###
