"""add category

Revision ID: c03781edf1d3
Revises: f712116fbc8f
Create Date: 2020-09-21 22:01:27.614444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03781edf1d3'
down_revision = 'f712116fbc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('podcast', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'podcast', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcast', type_='foreignkey')
    op.drop_column('podcast', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
