"""replies

Revision ID: cbaebdd5d908
Revises: f80f99a150e0
Create Date: 2020-10-12 21:36:21.525745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaebdd5d908'
down_revision = 'f80f99a150e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('original', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original'], ['comment.id'], name=op.f('fk_replies_original_comment')),
    sa.ForeignKeyConstraint(['reply'], ['comment.id'], name=op.f('fk_replies_reply_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    # ### end Alembic commands ###
