"""podcast table v3

Revision ID: cc351ca20ad1
Revises: 74ae942db114
Create Date: 2020-09-05 21:19:34.136321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc351ca20ad1'
down_revision = '74ae942db114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('author', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'author')
    # ### end Alembic commands ###
