"""add description to episode

Revision ID: cd73e648ad4c
Revises: ff7ed57a2aed
Create Date: 2020-09-12 17:44:38.392326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd73e648ad4c'
down_revision = 'ff7ed57a2aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('description', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'description')
    # ### end Alembic commands ###
