"""empty message

Revision ID: dad77bf8c832
Revises: 4a8915d7275d
Create Date: 2020-09-21 22:36:05.218701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad77bf8c832'
down_revision = '4a8915d7275d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'podcast', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcast', type_='foreignkey')
    # ### end Alembic commands ###
