"""comments

Revision ID: dd4c3d420cf0
Revises: 8c635889a70f
Create Date: 2020-10-07 23:08:34.980459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4c3d420cf0'
down_revision = '8c635889a70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_episode_id_episode'), 'episode', ['episode_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_episode_id_episode'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('episode_id')

    # ### end Alembic commands ###
