"""episode image

Revision ID: f712116fbc8f
Revises: 2437946eb6eb
Create Date: 2020-09-20 19:18:51.534088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f712116fbc8f'
down_revision = '2437946eb6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'image')
    # ### end Alembic commands ###
