"""recreate episode table

Revision ID: ff7ed57a2aed
Revises: b109364f45b4
Create Date: 2020-09-12 17:42:10.107460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7ed57a2aed'
down_revision = 'b109364f45b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('audio_link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_timestamp'), 'episode', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_timestamp'), table_name='episode')
    op.drop_table('episode')
    # ### end Alembic commands ###
